147.94.38.3
0
[VideoWindows]
[Audio Position]
[Audio Settings]
[Compressor Settings]
[Video Codecs]
[Capture Settings]
[Connect Options]
[Debug Controls]
[Debug Flags]
[Debug Options]
[Debug Position]
[Devices]
[drivers]
[Flow Control]
[Menu Position]
[MRU List]
[Participants Position]
[Participants Window]
[Settings]
[WhitePINEBoard]
[Local Position]
[Video Position]
[Multicast]
[PhoneBook Position]
[ChatLog]
[ChatLogFont]
[Chat Position]
[Directory Services]
[Listener]
